import { ITipping } from "../interfece/tipping";

export const getTippings = (): Promise<ITipping[]> => {
  return Promise.resolve([
    {
      nr: 1,
      hjemmelag: "Jerv",
      bortelag: "Vålerenga",
      dato: "2022-07-30-20-00",
      tips: {
        expertHomeTip: 22,
        expertDrawTip: 24,
        expertAwayTip: 54,
        peopleHomeTip: 18,
        peopleDrawTip: 17,
        peopleAwayTip: 65,
      },
    },
    {
      nr: 2,
      hjemmelag: "Aalesund",
      bortelag: "Bodø/Glimt",
      dato: "2022-07-30-16-00",
      tips: {
        expertHomeTip: 19,
        expertDrawTip: 22,
        expertAwayTip: 59,
        peopleHomeTip: 16,
        peopleDrawTip: 18,
        peopleAwayTip: 66,
      },
    },
    {
      nr: 3,
      hjemmelag: "HamKam",
      bortelag: "Kristiansund",
      dato: "2022-07-30-18-00",
      tips: {
        expertHomeTip: 67,
        expertDrawTip: 18,
        expertAwayTip: 15,
        peopleHomeTip: 65,
        peopleDrawTip: 19,
        peopleAwayTip: 16,
      },
    },
    {
      nr: 4,
      hjemmelag: "Odd",
      bortelag: "Rosenborg",
      dato: "2022-07-30-18-00",
      tips: {
        expertHomeTip: 31,
        expertDrawTip: 29,
        expertAwayTip: 40,
        peopleHomeTip: 24,
        peopleDrawTip: 27,
        peopleAwayTip: 49,
      },
    },
    {
      nr: 5,
      hjemmelag: "Tromsø",
      bortelag: "Sandefjord",
      dato: "2022-07-30-18-00",
      tips: {
        expertHomeTip: 63,
        expertDrawTip: 20,
        expertAwayTip: 17,
        peopleHomeTip: 55,
        peopleDrawTip: 23,
        peopleAwayTip: 22,
      },
    },
    {
      nr: 6,
      hjemmelag: "Liverpool",
      bortelag: "Manchester City",
      dato: "2022-07-30-18-00",
      tips: {
        expertHomeTip: 35,
        expertDrawTip: 30,
        expertAwayTip: 35,
        peopleHomeTip: 31,
        peopleDrawTip: 30,
        peopleAwayTip: 39,
      },
    },
    {
      nr: 7,
      hjemmelag: "Blackburn",
      bortelag: "Queens PR",
      dato: "2022-07-30-16-00",
      tips: {
        expertHomeTip: 51,
        expertDrawTip: 25,
        expertAwayTip: 24,
        peopleHomeTip: 59,
        peopleDrawTip: 22,
        peopleAwayTip: 19,
      },
    },
    {
      nr: 8,
      hjemmelag: "Cardiff",
      bortelag: "Norwich",
      dato: "2022-07-30-16-00",
      tips: {
        expertHomeTip: 26,
        expertDrawTip: 27,
        expertAwayTip: 47,
        peopleHomeTip: 28,
        peopleDrawTip: 27,
        peopleAwayTip: 45,
      },
    },
    {
      nr: 9,
      hjemmelag: "Hull",
      bortelag: "Bristol City",
      dato: "2022-07-30-16-00",
      tips: {
        expertHomeTip: 47,
        expertDrawTip: 27,
        expertAwayTip: 26,
        peopleHomeTip: 50,
        peopleDrawTip: 25,
        peopleAwayTip: 25,
      },
    },
    {
      nr: 10,
      hjemmelag: "Luton",
      bortelag: "Birmingham",
      dato: "2022-07-30-16-00",
      tips: {
        expertHomeTip: 52,
        expertDrawTip: 25,
        expertAwayTip: 23,
        peopleHomeTip: 60,
        peopleDrawTip: 21,
        peopleAwayTip: 19,
      },
    },
    {
      nr: 11,
      hjemmelag: "Millwall",
      bortelag: "Stoke",
      dato: "2022-07-30-16-00",
      tips: {
        expertHomeTip: 40,
        expertDrawTip: 29,
        expertAwayTip: 31,
        peopleHomeTip: 45,
        peopleDrawTip: 31,
        peopleAwayTip: 24,
      },
    },
    {
      nr: 12,
      hjemmelag: "Middlesbrough",
      bortelag: "West Bromwich",
      dato: "2022-07-30-18-30",
      tips: {
        expertHomeTip: 40,
        expertDrawTip: 29,
        expertAwayTip: 31,
        peopleHomeTip: 46,
        peopleDrawTip: 29,
        peopleAwayTip: 25,
      },
    },
  ]);
};
